In [1]:
import pandas as pd

In [2]:
hospitaldata = pd.read_csv('Hospital_General_Information.csv', encoding="ISO-8859-1")
hospitaldata

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,10001,SOUTHEAST ALABAMA MEDICAL CENTER,1108 ROSS CLARK CIRCLE,DOTHAN,AL,36301,HOUSTON,3347938701,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
1,10005,MARSHALL MEDICAL CENTER SOUTH,2505 U S HIGHWAY 431 NORTH,BOAZ,AL,35957,MARSHALL,2565938310,Acute Care Hospitals,Government - Hospital District or Authority,...,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Below the national average,NaN
2,10006,ELIZA COFFEE MEMORIAL HOSPITAL,205 MARENGO STREET,FLORENCE,AL,35631,LAUDERDALE,2567688400,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Above the national average,NaN,Same as the national average,NaN
3,10007,MIZELL MEMORIAL HOSPITAL,702 N MAIN ST,OPP,AL,36467,COVINGTON,3344933541,Acute Care Hospitals,Voluntary non-profit - Private,...,Below the national average,NaN,Same as the national average,NaN,Below the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
4,10008,CRENSHAW COMMUNITY HOSPITAL,101 HOSPITAL CIRCLE,LUVERNE,AL,36049,CRENSHAW,3343353374,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Above the national average,NaN,Not Available,Results are not available for this reporting p...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,670118,FIRST TEXAS HOSPITAL,9922 LOUETTA RD,HOUSTON,TX,77070,HARRIS,8442641435,Acute Care Hospitals,Proprietary,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4808,640001,LBJ TROPICAL MEDICAL CENTER,FAGAALU VILLAGE,PAGO PAGO,AS,96799,NaN,6846334590,Acute Care Hospitals,Government - Hospital District or Authority,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4809,650001,GUAM MEMORIAL HOSPITAL AUTHORITY,85O GOV CARLOS G CAMACHO ROAD,TAMUNING,GU,96913,NaN,6716472552,Acute Care Hospitals,Government - Local,...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Same as the national average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4810,650003,GUAM REGIONAL MEDICAL CITY,133 ROUTE 3,DEDEDO,GU,96929,NaN,6716455500,Acute Care Hospitals,Voluntary non-profit - Private,...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...
4811,660001,COMMONWEALTH HEALTH CENTER,"PO BOX 409CK, NAVY HILL ROAD",GARAPAN,MP,96950,NaN,6702348950,Acute Care Hospitals,Proprietary,...,Below the national average,NaN,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...

In [3]:
hospitaldata.isnull()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,True,False,True,False,True
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,True,False,True,False,True
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,True,False,True,False,True
3,False,False,False,False,False,False,False,False,False,False,...,False,True,False,True,False,True,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,True,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4808,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4809,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,True,False,False,False,False
4810,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4811,False,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [4]:
hospitaldata.isnull().sum()

Provider ID                                                         0
Hospital Name                                                       0
Address                                                             0
City                                                                0
State                                                               0
ZIP Code                                                            0
County Name                                                        15
Phone Number                                                        0
Hospital Type                                                       0
Hospital Ownership                                                  0
Emergency Services                                                  0
Meets criteria for meaningful use of EHRs                         143
Hospital overall rating                                             0
Hospital overall rating footnote                                 3414
Mortality national comparison                                       0
Mortality national comparison footnote                           3460
Safety of care national comparison                                  0
Safety of care national comparison footnote                      2644
Readmission national comparison                                     0
Readmission national comparison footnote                         3795
Patient experience national comparison                              0
Patient experience national comparison footnote                  3443
Effectiveness of care national comparison                           0
Effectiveness of care national comparison footnote               3610
Timeliness of care national comparison                              0
Timeliness of care national comparison footnote                  3546
Efficient use of medical imaging national comparison                0
Efficient use of medical imaging national comparison footnote    2779
dtype: int64

In [5]:
hospitaldata.notnull()

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
0,True,True,True,True,True,True,True,True,True,True,...,True,False,True,False,True,False,True,False,True,False
1,True,True,True,True,True,True,True,True,True,True,...,True,False,True,False,True,False,True,False,True,False
2,True,True,True,True,True,True,True,True,True,True,...,True,False,True,False,True,False,True,False,True,False
3,True,True,True,True,True,True,True,True,True,True,...,True,False,True,False,True,False,True,False,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,False,True,True,True,False,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4808,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4809,True,True,True,True,True,True,False,True,True,True,...,True,False,True,True,True,False,True,True,True,True
4810,True,True,True,True,True,True,False,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4811,True,True,True,True,True,True,False,True,True,True,...,True,False,True,True,True,True,True,True,True,True

In [6]:
hospitaldata2=hospitaldata.groupby(['Hospital Ownership','Hospital Type']).size()
hospitaldata2

Hospital Ownership                           Hospital Type
Government - Federal                         Acute Care Hospitals           37
                                             Critical Access Hospitals       8
Government - Hospital District or Authority  Acute Care Hospitals          273
                                             Childrens                       1
                                             Critical Access Hospitals     287
Government - Local                           Acute Care Hospitals          176
                                             Critical Access Hospitals     231
Government - State                           Acute Care Hospitals           50
                                             Childrens                       3
                                             Critical Access Hospitals      12
Physician                                    Acute Care Hospitals           65
                                             Critical Access Hospitals       3
Proprietary                                  Acute Care Hospitals          725
                                             Childrens                       8
                                             Critical Access Hospitals      67
Tribal                                       Acute Care Hospitals            5
                                             Critical Access Hospitals       4
Voluntary non-profit - Church                Acute Care Hospitals          278
                                             Childrens                       1
                                             Critical Access Hospitals      64
Voluntary non-profit - Other                 Acute Care Hospitals          359
                                             Childrens                      16
                                             Critical Access Hospitals      87
Voluntary non-profit - Private               Acute Care Hospitals         1401
                                             Childrens                      70
                                             Critical Access Hospitals     581
dtype: int64

In [7]:
hospitaldata3 = hospitaldata.groupby(['State']).size()
hospitaldata3

State
AK     22
AL     90
AR     75
AS      1
AZ     80
CA    343
CO     78
CT     31
DC      8
DE      7
FL    187
GA    133
GU      2
HI     23
IA    116
ID     41
IL    180
IN    120
KS    137
KY     94
LA    121
MA     64
MD     49
ME     33
MI    131
MN    131
MO    112
MP      1
MS     95
MT     62
NC    107
ND     44
NE     89
NH     26
NJ     66
NM     41
NV     35
NY    171
OH    168
OK    124
OR     60
PA    171
PR     52
RI     11
SC     60
SD     60
TN    107
TX    411
UT     46
VA     86
VI      2
VT     14
WA     91
WI    126
WV     49
WY     28
dtype: int64

In [8]:
hospitaldata4 = hospitaldata[hospitaldata['State'] == 'TX']
hospitaldata4

,Provider ID,Hospital Name,Address,City,State,ZIP Code,County Name,Phone Number,Hospital Type,Hospital Ownership,...,Readmission national comparison,Readmission national comparison footnote,Patient experience national comparison,Patient experience national comparison footnote,Effectiveness of care national comparison,Effectiveness of care national comparison footnote,Timeliness of care national comparison,Timeliness of care national comparison footnote,Efficient use of medical imaging national comparison,Efficient use of medical imaging national comparison footnote
3954,450002,PROVIDENCE MEMORIAL HOSPITAL,2001 N OREGON ST,EL PASO,TX,79902,EL PASO,9155776011,Acute Care Hospitals,Proprietary,...,Same as the national average,NaN,Below the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
3955,450007,PETERSON REGIONAL MEDICAL CENTER,551 HILL COUNTRY DRIVE,KERRVILLE,TX,78028,KERR,8308964200,Acute Care Hospitals,Voluntary non-profit - Private,...,Above the national average,NaN,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
3956,450010,UNITED REGIONAL HEALTH CARE SYSTEM,1600 11TH STREET,WICHITA FALLS,TX,76301,WICHITA,9407643055,Acute Care Hospitals,Voluntary non-profit - Private,...,Above the national average,NaN,Above the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
3957,450011,ST JOSEPH REGIONAL HEALTH CENTER,2801 FRANCISCAN DR,BRYAN,TX,77802,BRAZOS,9797763912,Acute Care Hospitals,Voluntary non-profit - Private,...,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN,Same as the national average,NaN
3958,450015,PARKLAND HEALTH AND HOSPITAL SYSTEM,5200 HARRY HINES BLVD,DALLAS,TX,75235,DALLAS,2145908000,Acute Care Hospitals,Government - Hospital District or Authority,...,Same as the national average,NaN,Below the national average,NaN,Below the national average,NaN,Below the national average,NaN,Same as the national average,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4803,670114,WEIMAR MEDICAL CENTER,400 YOUENS DR,WEIMAR,TX,78962,COLORADO,9797258274,Acute Care Hospitals,Proprietary,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4804,670115,CLEVELAND EMERGENCY HOSPTIAL,1017 S TRAVIS AVE,CLEVELAND,TX,77327,LIBERTY,2816595400,Acute Care Hospitals,Proprietary,...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...,Not Available,Data are shown only for hospitals that partici...
4805,670116,WISE HEALTH SYSTEM,3200 NORTH TARRANT PARKWAY,FORT WORTH,TX,76177,TARRANT,8175027300,Acute Care Hospitals,Government - Hospital District or Authority,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4806,670117,TEXAS GENERAL HOSPITAL- VZRMC LP,707 N WALDRIP ST,GRAND SALINE,TX,75140,VAN ZANDT,9039625200,Acute Care Hospitals,Proprietary,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...
4807,670118,FIRST TEXAS HOSPITAL,9922 LOUETTA RD,HOUSTON,TX,77070,HARRIS,8442641435,Acute Care Hospitals,Proprietary,...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...,Not Available,Results are not available for this reporting p...

In [9]:
hospitaldata5n=hospitaldata[['State','Hospital Ownership']]
hospitaldata5=hospitaldata5n[hospitaldata['State']=='TX']
hospitaldata5

,State,Hospital Ownership
3954,TX,Proprietary
3955,TX,Voluntary non-profit - Private
3956,TX,Voluntary non-profit - Private
3957,TX,Voluntary non-profit - Private
3958,TX,Government - Hospital District or Authority
...,...,...
4803,TX,Proprietary
4804,TX,Proprietary
4805,TX,Government - Hospital District or Authority
4806,TX,Proprietary
4807,TX,Proprietary

In [10]:
hospitaldata6=pd.crosstab(hospitaldata["Hospital Name"],hospitaldata['Timeliness of care national comparison footnote']=='Above the national average')
hospitaldata6

Timeliness of care national comparison footnote,False
Hospital Name,
ABBEVILLE AREA MEDICAL CENTER,1
ABBEVILLE GENERAL HOSPITAL,1
ABBOTT NORTHWESTERN HOSPITAL,1
ABILENE REGIONAL MEDICAL CENTER,1
ABINGTON MEMORIAL HOSPITAL,1
...,...
YORK HOSPITAL,2
YUKON KUSKOKWIM DELTA REG HOSPITAL,1
YUMA DISTRICT HOSPITAL,1
YUMA REGIONAL MEDICAL CENTER,1
ZUNI COMPREHENSIVE COMMUNITY HEALTH CENTER,1

In [11]:
hospital_ratings =  hospitaldata[['Hospital Name','Hospital overall rating']]
hospital_ratings

,Hospital Name,Hospital overall rating
0,SOUTHEAST ALABAMA MEDICAL CENTER,3
1,MARSHALL MEDICAL CENTER SOUTH,3
2,ELIZA COFFEE MEMORIAL HOSPITAL,2
3,MIZELL MEMORIAL HOSPITAL,2
4,CRENSHAW COMMUNITY HOSPITAL,3
...,...,...
4807,FIRST TEXAS HOSPITAL,Not Available
4808,LBJ TROPICAL MEDICAL CENTER,Not Available
4809,GUAM MEMORIAL HOSPITAL AUTHORITY,3
4810,GUAM REGIONAL MEDICAL CITY,Not Available
4811,COMMONWEALTH HEALTH CENTER,Not Available

In [12]:
hospitaldata8=hospitaldata.loc[(hospitaldata["Hospital Type"]=="Acute Care Hospitals")&(hospitaldata["Hospital overall rating"]=="4"),["Hospital Name","State"]]
hospitaldata8

,Hospital Name,State
10,DALE MEDICAL CENTER,AL
11,CHEROKEE MEDICAL CENTER,AL
14,EAST ALABAMA MEDICAL CENTER,AL
15,WEDOWEE HOSPITAL,AL
17,COMMUNITY HOSPITAL INC,AL
...,...,...
4777,BAPTIST EMERGENCY HOSPITAL,TX
4779,SETON MEDICAL CENTER HARKER HEIGHTS,TX
4780,BAYLOR SCOTT AND WHITE MEDICAL CENTER MCKINNEY,TX
4782,TEXAS HEALTH HARRIS METHODIST HOSPITAL ALLIANCE,TX
4784,BAYLOR SCOTT & WHITE MEDICAL CENTER- COLLEGE S...,TX

In [13]:
hospitaldata9n = hospitaldata[hospitaldata['Safety of care national comparison']=='Not Available']
hospitaldata9 = hospitaldata9n.groupby('Hospital Type').size()
hospitaldata9

Hospital Type
Acute Care Hospitals          727
Childrens                      99
Critical Access Hospitals    1342
dtype: int64

In [14]:
hospitaldata10=hospitaldata.loc[:,['Provider ID','Patient experience national comparison']]
hospitaldata10

,Provider ID,Patient experience national comparison
0,10001,Below the national average
1,10005,Same as the national average
2,10006,Below the national average
3,10007,Same as the national average
4,10008,Not Available
...,...,...
4807,670118,Not Available
4808,640001,Not Available
4809,650001,Not Available
4810,650003,Not Available
4811,660001,Not Available